### ISSUE TITLE
TypeError: unsupported operand type

### ISSUE THREAD

**Issue by jli113** [Al-Taie/quick-mailer#1]
**Describe the bug**
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**To Reproduce**
from mailer import Mailer

mail = Mailer(email='sender', password='password')
mail.settings(provider=mail.MICROSOFT)
mail.send(receiver='receiver', subject='TEST', message='From Python')

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33822210/151912023-c052bd1d-62a2-4ac4-8d4f-b12a44dcc45c.png)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome
 - Version 97.0.4692.71

**Additional context**

**Comment by Al-Taie** [comment]
**fixed, thanks** 
**if you see this project useful please put a star🌟**

**Comment by jli113** [comment]
Still having the same error with version 2022.2.2

**Comment by Al-Taie** [comment]
> Still having the same error with version 2022.2.2

**Fixed thanks for report, update to new version.**
```
pip install -U quick-mailer
```
OR
```
pip install quick-mailer==2022.2.10
```
